/* This file is automatically generated by Lemon from input grammar
** source file "arith/arith.parser_lemon.y".
*/
// -*- mode: c -*-
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifier prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#include <assert.h>
#include <stdio.h> // parsetrace uses FILE
#include <stdlib.h>

#if INTERFACE
// Things to inject into makeheaders exported interface
#ifndef YYMALLOCARGTYPE
#define YYMALLOCARGTYPE size_t
#endif

#include "../tools/token.h"

// typedef union arith_parser_lemon_u arith_parser_lemon_type;

struct arith_parser_lemon_state;

typedef struct arith_parser_lemon_state arith_parser_lemon_state;

#endif // end INTERFACE


#define arith_Lemon_ENGINEALWAYSONSTACK 1 // Remove LemonAlloc

#include "../tools/token.h"


#include "arith.lexer.h"
#include "arith.parser.h"
#include "arith.productions.h"
#include "arith.production_tree.h"

__attribute__((unused)) static int arith_LemonFallback(int);

struct yyParser;
enum {verbose_error = 0,};
__attribute__((unused)) static void arith_LemonFailure(struct yyParser *);
__attribute__((unused)) static void arith_LemonStackOverflow(struct yyParser *);

static void arith_LemonFinalize(void *p);
static void arith_LemonInit(void *);
static void arith_Lemon(void*, int, token, struct arith_parse_state *);

      
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef TOKEN_ID_PLUS
#define TOKEN_ID_PLUS                            1
#define TOKEN_ID_MINUS                           2
#define TOKEN_ID_TIMES                           3
#define TOKEN_ID_DIVIDE                          4
#define TOKEN_ID_REMAINDER                       5
#define TOKEN_ID_BITOR                           6
#define TOKEN_ID_BITAND                          7
#define TOKEN_ID_BITXOR                          8
#define TOKEN_ID_ABSOLUTE                        9
#define TOKEN_ID_NEGATE                         10
#define TOKEN_ID_INCREMENT                      11
#define TOKEN_ID_DECREMENT                      12
#define TOKEN_ID_INTEGER                        13
#define TOKEN_ID_SPACE                          14
#define TOKEN_ID_NEWLINE                        15
#define TOKEN_ID_CONTROL                        16
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    arith_LemonTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is arith_LemonTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    arith_LemonARG_SDECL     A static variable declaration for the %extra_argument
**    arith_LemonARG_PDECL     A parameter declaration for the %extra_argument
**    arith_LemonARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    arith_LemonARG_STORE     Code to store %extra_argument into yypParser
**    arith_LemonARG_FETCH     Code to extract %extra_argument from yypParser
**    arith_LemonCTX_*         As arith_LemonARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 21
#define YYACTIONTYPE unsigned char
#define arith_LemonTOKENTYPE  token 
typedef union {
  int yyinit;
  arith_LemonTOKENTYPE yy0;
  proto yy9;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 0
#endif
#define arith_LemonARG_SDECL struct arith_parse_state * context;
#define arith_LemonARG_PDECL ,struct arith_parse_state * context
#define arith_LemonARG_PARAM ,context
#define arith_LemonARG_FETCH struct arith_parse_state * context=yypParser->context; (void)context;
#define arith_LemonARG_STORE yypParser->context=context;
#define arith_LemonCTX_SDECL
#define arith_LemonCTX_PDECL
#define arith_LemonCTX_PARAM
#define arith_LemonCTX_FETCH
#define arith_LemonCTX_STORE
#define YYNSTATE             63
#define YYNRULE              18
#define YYNRULE_WITH_ACTION  18
#define YYNTOKEN             17
#define YY_MAX_SHIFT         62
#define YY_MIN_SHIFTREDUCE   77
#define YY_MAX_SHIFTREDUCE   94
#define YY_ERROR_ACTION      95
#define YY_ACCEPT_ACTION     96
#define YY_NO_ACTION         97
#define YY_MIN_REDUCE        98
#define YY_MAX_REDUCE        115
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (123)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */    24,   59,   56,   53,   50,   47,   44,   41,   38,   35,
 /*    10 */    33,   31,   29,   81,   26,   25,   82,   60,   59,   56,
 /*    20 */    53,   50,   47,   44,   41,   38,   35,   33,   31,   29,
 /*    30 */    81,   59,   56,   53,   50,   47,   44,   41,   38,   35,
 /*    40 */    33,   31,   29,   96,   62,   61,   27,   81,   28,   97,
 /*    50 */    30,   32,   34,  101,   36,   37,   39,   40,   42,   43,
 /*    60 */    45,   46,   48,   49,   51,   52,   54,   55,   57,    2,
 /*    70 */    58,  100,    1,   97,   94,    4,   97,   93,    5,   97,
 /*    80 */    92,    6,   97,   91,    7,   97,   97,   90,   89,    8,
 /*    90 */     9,   97,   10,   11,   97,   97,   88,   87,   12,   13,
 /*   100 */    97,   97,   14,   15,   97,   86,   85,   16,   17,   99,
 /*   110 */    98,   18,   19,   97,   84,   83,   97,   20,   21,   97,
 /*   120 */    22,   23,    3,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    18,    1,    2,    3,    4,    5,    6,    7,    8,    9,
 /*    10 */    10,   11,   12,   13,   18,   19,   16,   18,    1,    2,
 /*    20 */     3,    4,    5,    6,    7,    8,    9,   10,   11,   12,
 /*    30 */    13,    1,    2,    3,    4,    5,    6,    7,    8,    9,
 /*    40 */    10,   11,   12,   17,   18,   19,   20,   13,   19,   21,
 /*    50 */    19,   19,   19,    0,   19,   19,   19,   19,   19,   19,
 /*    60 */    19,   19,   19,   19,   19,   19,   19,   19,   19,   14,
 /*    70 */    19,    0,   14,   21,   15,   14,   21,   15,   14,   21,
 /*    80 */    15,   14,   21,   15,   14,   21,   21,   15,   15,   14,
 /*    90 */    14,   21,   14,   14,   21,   21,   15,   15,   14,   14,
 /*   100 */    21,   21,   14,   14,   21,   15,   15,   14,   14,    0,
 /*   110 */     0,   14,   14,   21,   15,   15,   21,   14,   14,   21,
 /*   120 */    14,   14,   14,   21,   21,   21,   21,   21,   21,   21,
 /*   130 */    21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
};
#define YY_SHIFT_COUNT    (62)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (110)
static const unsigned char yy_shift_ofst[] = {
 /*     0 */     0,   17,   30,   30,   34,   34,   34,   34,   34,   34,
 /*    10 */    34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
 /*    20 */    34,   34,   34,   34,   53,   55,   71,   58,   59,   61,
 /*    30 */    62,   64,   65,   67,   68,   70,   72,   75,   76,   73,
 /*    40 */    78,   79,   81,   84,   85,   82,   88,   89,   90,   93,
 /*    50 */    94,   91,   97,   98,   99,  103,  104,  100,  106,  107,
 /*    60 */   109,  108,  110,
};
#define YY_REDUCE_COUNT (23)
#define YY_REDUCE_MIN   (-18)
#define YY_REDUCE_MAX   (51)
static const signed char yy_reduce_ofst[] = {
 /*     0 */    26,   -4,  -18,   -1,   29,   31,   32,   33,   35,   36,
 /*    10 */    37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
 /*    20 */    47,   48,   49,   51,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */    95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
 /*    10 */    95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
 /*    20 */    95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
 /*    30 */    95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
 /*    40 */    95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
 /*    50 */    95,   95,   95,   95,   95,   95,   95,   95,   95,   95,
 /*    60 */    95,   95,   95,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  arith_LemonARG_SDECL                /* A place to hold %extra_argument */
  arith_LemonCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#if __STDC_HOSTED__

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void arith_LemonTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#endif // __STDC_HOSTED__


#if __STDC_HOSTED__
#if defined(YYCOVERAGE)
#undef YYCOVERAGE
#endif
#endif

#if __STDC_HOSTED__
#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "PLUS",
  /*    2 */ "MINUS",
  /*    3 */ "TIMES",
  /*    4 */ "DIVIDE",
  /*    5 */ "REMAINDER",
  /*    6 */ "BITOR",
  /*    7 */ "BITAND",
  /*    8 */ "BITXOR",
  /*    9 */ "ABSOLUTE",
  /*   10 */ "NEGATE",
  /*   11 */ "INCREMENT",
  /*   12 */ "DECREMENT",
  /*   13 */ "INTEGER",
  /*   14 */ "SPACE",
  /*   15 */ "NEWLINE",
  /*   16 */ "CONTROL",
  /*   17 */ "program",
  /*   18 */ "expr",
  /*   19 */ "integer",
  /*   20 */ "control_block",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */
#endif

#if __STDC_HOSTED__
#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "program ::= expr",
 /*   1 */ "program ::= integer SPACE expr",
 /*   2 */ "program ::= control_block SPACE expr",
 /*   3 */ "program ::= control_block SPACE integer SPACE expr",
 /*   4 */ "integer ::= INTEGER",
 /*   5 */ "control_block ::= CONTROL",
 /*   6 */ "expr ::= PLUS SPACE integer SPACE integer NEWLINE",
 /*   7 */ "expr ::= MINUS SPACE integer SPACE integer NEWLINE",
 /*   8 */ "expr ::= TIMES SPACE integer SPACE integer NEWLINE",
 /*   9 */ "expr ::= DIVIDE SPACE integer SPACE integer NEWLINE",
 /*  10 */ "expr ::= REMAINDER SPACE integer SPACE integer NEWLINE",
 /*  11 */ "expr ::= BITOR SPACE integer SPACE integer NEWLINE",
 /*  12 */ "expr ::= BITAND SPACE integer SPACE integer NEWLINE",
 /*  13 */ "expr ::= BITXOR SPACE integer SPACE integer NEWLINE",
 /*  14 */ "expr ::= ABSOLUTE SPACE integer NEWLINE",
 /*  15 */ "expr ::= NEGATE SPACE integer NEWLINE",
 /*  16 */ "expr ::= INCREMENT SPACE integer NEWLINE",
 /*  17 */ "expr ::= DECREMENT SPACE integer NEWLINE",
};
#endif /* NDEBUG */
#endif

#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#if __STDC_HOSTED__
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to arith_LemonAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void arith_LemonInit(void *yypRawParser arith_LemonCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  arith_LemonCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef arith_Lemon_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to arith_Lemon and arith_LemonFree.
*/
void *arith_LemonAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) arith_LemonCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    arith_LemonCTX_STORE
    arith_LemonInit(yypParser arith_LemonCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* arith_Lemon_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  arith_LemonARG_FETCH
  arith_LemonCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#if __STDC_HOSTED__
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void arith_LemonFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef arith_Lemon_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void arith_LemonFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  arith_LemonFinalize(p);
  (*freeProc)(p);
}
#endif /* arith_Lemon_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int arith_LemonStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int arith_LemonCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
#if __STDC_HOSTED__
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
        
      }
#endif
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#if __STDC_HOSTED__
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#if __STDC_HOSTED__
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
#endif
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   arith_LemonARG_FETCH
   arith_LemonCTX_FETCH
#if __STDC_HOSTED__
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
 arith_LemonStackOverflow(yypParser); 
/******** End %stack_overflow code ********************************************/
   arith_LemonARG_STORE /* Suppress warning about unused %extra_argument var */
   arith_LemonCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#if __STDC_HOSTED__
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif
#else
# define yyTraceShift(X,Y,Z)
#endif
/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  arith_LemonTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    17,  /* (0) program ::= expr */
    17,  /* (1) program ::= integer SPACE expr */
    17,  /* (2) program ::= control_block SPACE expr */
    17,  /* (3) program ::= control_block SPACE integer SPACE expr */
    19,  /* (4) integer ::= INTEGER */
    20,  /* (5) control_block ::= CONTROL */
    18,  /* (6) expr ::= PLUS SPACE integer SPACE integer NEWLINE */
    18,  /* (7) expr ::= MINUS SPACE integer SPACE integer NEWLINE */
    18,  /* (8) expr ::= TIMES SPACE integer SPACE integer NEWLINE */
    18,  /* (9) expr ::= DIVIDE SPACE integer SPACE integer NEWLINE */
    18,  /* (10) expr ::= REMAINDER SPACE integer SPACE integer NEWLINE */
    18,  /* (11) expr ::= BITOR SPACE integer SPACE integer NEWLINE */
    18,  /* (12) expr ::= BITAND SPACE integer SPACE integer NEWLINE */
    18,  /* (13) expr ::= BITXOR SPACE integer SPACE integer NEWLINE */
    18,  /* (14) expr ::= ABSOLUTE SPACE integer NEWLINE */
    18,  /* (15) expr ::= NEGATE SPACE integer NEWLINE */
    18,  /* (16) expr ::= INCREMENT SPACE integer NEWLINE */
    18,  /* (17) expr ::= DECREMENT SPACE integer NEWLINE */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) program ::= expr */
   -3,  /* (1) program ::= integer SPACE expr */
   -3,  /* (2) program ::= control_block SPACE expr */
   -5,  /* (3) program ::= control_block SPACE integer SPACE expr */
   -1,  /* (4) integer ::= INTEGER */
   -1,  /* (5) control_block ::= CONTROL */
   -6,  /* (6) expr ::= PLUS SPACE integer SPACE integer NEWLINE */
   -6,  /* (7) expr ::= MINUS SPACE integer SPACE integer NEWLINE */
   -6,  /* (8) expr ::= TIMES SPACE integer SPACE integer NEWLINE */
   -6,  /* (9) expr ::= DIVIDE SPACE integer SPACE integer NEWLINE */
   -6,  /* (10) expr ::= REMAINDER SPACE integer SPACE integer NEWLINE */
   -6,  /* (11) expr ::= BITOR SPACE integer SPACE integer NEWLINE */
   -6,  /* (12) expr ::= BITAND SPACE integer SPACE integer NEWLINE */
   -6,  /* (13) expr ::= BITXOR SPACE integer SPACE integer NEWLINE */
   -4,  /* (14) expr ::= ABSOLUTE SPACE integer NEWLINE */
   -4,  /* (15) expr ::= NEGATE SPACE integer NEWLINE */
   -4,  /* (16) expr ::= INCREMENT SPACE integer NEWLINE */
   -4,  /* (17) expr ::= DECREMENT SPACE integer NEWLINE */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  arith_LemonTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  arith_LemonCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  arith_LemonARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* program ::= expr */
{

  yylhsminor.yy9 = arith_assign_production_expr_to_program(context, yymsp[0].minor.yy9);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[0].minor.yy9 = yylhsminor.yy9;
        break;
      case 1: /* program ::= integer SPACE expr */
{

  yylhsminor.yy9 = arith_custom_production_result_expr_to_program(context, yymsp[-2].minor.yy9, yymsp[-1].minor.yy0, yymsp[0].minor.yy9);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-2].minor.yy9 = yylhsminor.yy9;
        break;
      case 2: /* program ::= control_block SPACE expr */
{

  yylhsminor.yy9 = arith_custom_production_control_expr_to_program(context, yymsp[-2].minor.yy9, yymsp[-1].minor.yy0, yymsp[0].minor.yy9);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-2].minor.yy9 = yylhsminor.yy9;
        break;
      case 3: /* program ::= control_block SPACE integer SPACE expr */
{

  yylhsminor.yy9 = arith_custom_production_control_result_expr_to_program(context, yymsp[-4].minor.yy9, yymsp[-3].minor.yy0, yymsp[-2].minor.yy9, yymsp[-1].minor.yy0, yymsp[0].minor.yy9);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-4].minor.yy9 = yylhsminor.yy9;
        break;
      case 4: /* integer ::= INTEGER */
{

  yylhsminor.yy9 = arith_custom_production_FromInteger(context, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[0].minor.yy9 = yylhsminor.yy9;
        break;
      case 5: /* control_block ::= CONTROL */
{

  yylhsminor.yy9 = arith_custom_production_FromControl(context, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[0].minor.yy9 = yylhsminor.yy9;
        break;
      case 6: /* expr ::= PLUS SPACE integer SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_BinOpPlus(context, yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[-3].minor.yy9, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-5].minor.yy9 = yylhsminor.yy9;
        break;
      case 7: /* expr ::= MINUS SPACE integer SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_BinOpMinus(context, yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[-3].minor.yy9, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-5].minor.yy9 = yylhsminor.yy9;
        break;
      case 8: /* expr ::= TIMES SPACE integer SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_BinOpTimes(context, yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[-3].minor.yy9, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-5].minor.yy9 = yylhsminor.yy9;
        break;
      case 9: /* expr ::= DIVIDE SPACE integer SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_BinOpDivide(context, yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[-3].minor.yy9, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-5].minor.yy9 = yylhsminor.yy9;
        break;
      case 10: /* expr ::= REMAINDER SPACE integer SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_BinOpRemainder(context, yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[-3].minor.yy9, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-5].minor.yy9 = yylhsminor.yy9;
        break;
      case 11: /* expr ::= BITOR SPACE integer SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_BinOpBitOr(context, yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[-3].minor.yy9, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-5].minor.yy9 = yylhsminor.yy9;
        break;
      case 12: /* expr ::= BITAND SPACE integer SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_BinOpBitAnd(context, yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[-3].minor.yy9, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-5].minor.yy9 = yylhsminor.yy9;
        break;
      case 13: /* expr ::= BITXOR SPACE integer SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_BinOpBitXor(context, yymsp[-5].minor.yy0, yymsp[-4].minor.yy0, yymsp[-3].minor.yy9, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-5].minor.yy9 = yylhsminor.yy9;
        break;
      case 14: /* expr ::= ABSOLUTE SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_UnOpAbsolute(context, yymsp[-3].minor.yy0, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-3].minor.yy9 = yylhsminor.yy9;
        break;
      case 15: /* expr ::= NEGATE SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_UnOpNegate(context, yymsp[-3].minor.yy0, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-3].minor.yy9 = yylhsminor.yy9;
        break;
      case 16: /* expr ::= INCREMENT SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_UnOpIncrement(context, yymsp[-3].minor.yy0, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-3].minor.yy9 = yylhsminor.yy9;
        break;
      case 17: /* expr ::= DECREMENT SPACE integer NEWLINE */
{

  yylhsminor.yy9 = arith_custom_production_UnOpDecrement(context, yymsp[-3].minor.yy0, yymsp[-2].minor.yy0, yymsp[-1].minor.yy9, yymsp[0].minor.yy0);
  if (!arith_parse_state_is_failure(context))
  {
    arith_parse_state_set_stored_tree(context, yylhsminor.yy9);
  }
}
  yymsp[-3].minor.yy9 = yylhsminor.yy9;
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  arith_LemonARG_FETCH
  arith_LemonCTX_FETCH
#if __STDC_HOSTED__
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
/************ End %parse_failure code *****************************************/
  arith_LemonARG_STORE /* Suppress warning about unused %extra_argument variable */
  arith_LemonCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  arith_LemonTOKENTYPE yyminor         /* The minor type of the error token */
){
  arith_LemonARG_FETCH
  arith_LemonCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
 arith_LemonFailure(yypParser); 
/************ End %syntax_error code ******************************************/
  arith_LemonARG_STORE /* Suppress warning about unused %extra_argument variable */
  arith_LemonCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  arith_LemonARG_FETCH
  arith_LemonCTX_FETCH
#if __STDC_HOSTED__
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
/*********** End %parse_accept code *******************************************/
  arith_LemonARG_STORE /* Suppress warning about unused %extra_argument variable */
  arith_LemonCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "arith_LemonAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void arith_Lemon(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  arith_LemonTOKENTYPE yyminor       /* The value for the token */
  arith_LemonARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  arith_LemonCTX_FETCH
  arith_LemonARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#if __STDC_HOSTED__
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#if __STDC_HOSTED__
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */
#endif

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor arith_LemonCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#if __STDC_HOSTED__
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#if __STDC_HOSTED__
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#if __STDC_HOSTED__
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int arith_LemonFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}



 __attribute__((unused)) static
void arith_LemonFailure(struct yyParser * yypParser)
{
  // struct arith_parse_state
  arith_LemonARG_FETCH

  arith_parse_state_set_stored_tree(context, arith_production_failure(context));

#if __STDC_HOSTED__
  if (verbose_error)
  {
    fprintf(stderr, "Lemon arith syntax error\n");
  }
#endif

  arith_LemonARG_STORE
}

 __attribute__((unused)) static
void arith_LemonStackOverflow(struct yyParser * yypParser)
{
  // struct arith_parse_state
  arith_LemonARG_FETCH

  arith_parse_state_set_stored_tree(context, arith_production_failure(context));

#if __STDC_HOSTED__
  if (verbose_error)
  {
    fprintf(stderr, "Lemon arith stack overflow\n");
  }
#endif

  arith_LemonARG_STORE
}


#include "arith.parser_lemon.h"

// Implementation of "arith.parser_lemon.t"
enum {
  arith_parser_lemon_type_align = _Alignof(struct yyParser),
  arith_parser_lemon_type_size = sizeof(struct yyParser),
};

struct arith_parser_lemon_state {
  char _Alignas(arith_parser_lemon_type_align) data[arith_parser_lemon_type_size];
};

// Type aliasing workaround
union arith_parser_lemon_u
{
  struct yyParser lemon;
  struct arith_parser_lemon_state state;
};

// Union is the same size, align as state
_Static_assert(sizeof(union arith_parser_lemon_u) == sizeof(struct yyParser),"");
_Static_assert(_Alignof(union arith_parser_lemon_u) == _Alignof(struct yyParser),"");

// Union is the same size, align as external type
_Static_assert(sizeof(union arith_parser_lemon_u) == arith_parser_lemon_type_size,"");
_Static_assert(_Alignof(union arith_parser_lemon_u) == arith_parser_lemon_type_align,"");

typedef union arith_parser_lemon_u union_type;

void arith_parser_lemon_initialize(arith_parser_lemon_state*a)
{
  union_type * p = (union_type*)a;
  arith_LemonInit(&p->lemon);
}
  
void arith_parser_lemon_finalize(arith_parser_lemon_state*a)
{
  union_type * p = (union_type*)a;
  arith_LemonFinalize(&p->lemon);
}

bool arith_parser_lemon_parse(struct arith_parse_state *context, arith_parser_lemon_state*a, int id, token t)
{
  union_type * p = (union_type*)a;
  assert(id > 0);

  const bool initially_failure = arith_parse_state_is_failure(context);
  if (!initially_failure)
  {
    // Then mark with sentinel
    arith_parse_state_set_stored_tree(context, proto_sentinel());
  }

  arith_Lemon(&p->lemon, id, t, context);

  proto res = arith_parse_state_get_stored_tree(context);

  if (initially_failure)
  {
    // parser cannot transition from failure to a different mode
    assert(arith_production_is_failure(context, res));
  }

  if (proto_is_sentinel(res)) {
    // Didn't write to it, i.e. no reduction and no error
    return true;
  }
  return !arith_production_is_failure(context, res);
}

proto arith_parser_lemon_tree(struct arith_parse_state *context, arith_parser_lemon_state*a)
{
  union_type * p = (union_type*)a;

  const bool initially_failure = arith_parse_state_is_failure(context);
  if (!initially_failure)
  {
    // Then mark with sentinel
    arith_parse_state_set_stored_tree(context, proto_sentinel());
  }

  token tok = token_create_novalue("");
  arith_Lemon(&p->lemon, 0, tok, context);

  proto res = arith_parse_state_get_stored_tree(context);

  if (initially_failure)
  {
    // parser cannot transition from failure to a different mode
    assert(arith_production_is_failure(context, res));
  }

  return res;
}

#if __STDC_HOSTED__
#include <stdio.h>
int arith_parser_lemon_type_header(void)
{
  return printf(
  "#ifndef ARITH_PARSER_LEMON_T_INCLUDED\n"
  "#define ARITH_PARSER_LEMON_T_INCLUDED\n"
  "\n"
  "enum {\n"
  "  arith_parser_lemon_type_align = %lu,\n"
  "  arith_parser_lemon_type_size = %lu,\n"
  "};\n"
  "struct arith_parser_lemon_state {\n"
  "    char _Alignas(arith_parser_lemon_type_align) data[arith_parser_lemon_type_size];\n"
  "};\n"
  "\n"
  "#endif\n",
  _Alignof(struct yyParser),
  sizeof(struct yyParser)) > 0 ? 0 : 1;
}

#ifndef NDEBUG
// Then _LemonTrace(...) is defined above
#else
// Define a stub
void arith_LemonTrace(FILE *TraceFILE, char *zTracePrompt)
{
  (void)TraceFILE;
  (void)zTracePrompt;
}
#endif

static char 
  arith_parser_lemon_trace_prefix[] = "arith: ";

void arith_parser_lemon_trace_on(void)
{
  arith_LemonTrace(stdout, arith_parser_lemon_trace_prefix);
}

void arith_parser_lemon_trace_off(void)
{
  arith_LemonTrace(0, arith_parser_lemon_trace_prefix);
}

#endif

proto arith_parser_lemon_parse_cstr(struct arith_parse_state * context, const char * data)
{
  size_t N = __builtin_strlen(data);
  lexer_t lexer = arith_lexer_create();
  if (!arith_lexer_valid(lexer)) { return arith_production_failure(context); }

  arith_parser_lemon_state parser;
  arith_parser_lemon_initialize(&parser);

  proto res = arith_production_failure(context);
  
  for (lexer_iterator_t lexer_iterator = lexer_iterator_t_create(data, N);
       !lexer_iterator_t_empty(lexer_iterator);) {
    lexer_token_t lexer_token =
      arith_lexer_iterator_step(lexer, &lexer_iterator);
    
    if (arith_lexer_discard_token(lexer_token.id)) {
      continue;
    }

    token lemon_token = token_create(arith_token_names[lexer_token.id],
                                     lexer_token.value, lexer_token.width);

    // 0 is the unknown token                                 
    if (lexer_token.id == 0) {
      arith_parser_lemon_finalize(&parser);
      arith_lexer_destroy(lexer);
      return arith_production_failure(context);
    }

    bool parse_ok = arith_parser_lemon_parse(context, &parser, (int)lexer_token.id, lemon_token);
    if (!parse_ok)
    {
      goto done;
    }
  }

  assert(arith_production_is_failure(context, res));
  res = arith_parser_lemon_tree(context, &parser);

  done:;
  arith_parser_lemon_finalize(&parser);
  arith_lexer_destroy(lexer);

  return res;
}

      
